import type { ScanReport } from "../core/types.js";

export function renderMarkdownPia(report: ScanReport): string {
  const activity = report.processingActivities[0];
  const personalData = unique(report.processingActivities.flatMap((item) => item.personalData.map((data) => data.field)));
  const complianceLines = Object.entries(report.complianceChecks).map(
    ([key, check]) => `- ${labelCheck(key)}: ${capitalize(check.status)} - ${check.reason}`
  );
  const riskLines = report.findings.map((finding, index) => `${index + 1}. ${finding.title}. ${finding.description}`);
  const flowLines = report.dataFlows.map((flow) => `- ${flow.from} -> ${flow.to}${flow.data.length > 0 ? ` (${flow.data.join(", ")})` : ""}`);
  const controlLines = report.recommendedControls.map((control) => `- [${control.priority}] ${control.control}`);
  const missingLines = report.missingEvidence.map((item) => `- ${item}`);

  return `# Privacy Impact Assessment Draft

> ${report.disclaimer}

Generated by code2pia on ${report.scan.startedAt}

Repository: \`${report.scan.repository}\`

Jurisdiction: ${report.jurisdiction.country} / ${report.jurisdiction.law}

## 1. Executive Summary

This repository ${personalData.length > 0 ? `appears to process personal data, including ${personalData.join(", ")}.` : "does not currently show personal data indicators under the active heuristics."} The current draft risk level is **${report.summary.overallRisk.toUpperCase()}**.

PIA / EIPD requirement: **${report.summary.requiresPIA.toUpperCase()}**.

This assessment is automatically generated and requires human review.

${report.summary.mainReasons.length > 0 ? ["Main reasons:", ...report.summary.mainReasons.map((reason) => `- ${reason}`)].join("\n") : ""}

## 2. Processing Description

Detected processing activity: ${activity?.name ?? "None detected"}.

Purpose: ${activity ? statusValue(activity.purpose.declared ?? activity.purpose.detected, activity.purpose.status) : "Not detected"}.

Lawful basis: ${activity ? statusValue(activity.lawfulBasis.declared ?? activity.lawfulBasis.detected, activity.lawfulBasis.status) : "Not detected"}.

Data subjects: ${activity?.dataSubjects.join(", ") ?? "Unknown"}.

## 3. Personal Data Detected

${personalData.length > 0 ? personalData.map((item) => `- ${item}`).join("\n") : "- No personal data indicators were detected."}

## 4. Data Flows

${flowLines.length > 0 ? flowLines.join("\n") : "- No data flows were inferred."}

## 5. Chilean Law 21.719 Review

Initial checks:

${complianceLines.join("\n")}

## 6. Risks Identified

${riskLines.length > 0 ? riskLines.join("\n") : "No risk patterns were detected by the current heuristics."}

## 7. Recommended Controls

${controlLines.length > 0 ? controlLines.join("\n") : "- No controls were generated by the current heuristics."}

## 8. Missing Evidence

${missingLines.length > 0 ? missingLines.join("\n") : "- No missing evidence was inferred."}

## 9. Human Review Checklist

- Is each detected field strictly necessary?
- Is the purpose specific and documented?
- Is there a valid lawful basis?
- Are logs protected from personal data exposure?
- Can the user access, correct, delete, oppose, block, or port their data?
- Are processors, third parties, and transfer safeguards documented?
- Are retention periods and deletion workflows documented?
`;
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

function labelCheck(key: string): string {
  return key.replace(/[A-Z]/g, (letter) => ` ${letter.toLowerCase()}`);
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function statusValue(value: string | null, status: string): string {
  if (status === "missing" || !value) {
    return "Not declared";
  }

  return value;
}
